name: Build and Upload to Windows Server

on:
  push:
    branches:
      - main

jobs:
  build-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install & Build React client
        run: |
          cd client
          npm install --legacy-peer-deps
          CI=false npm run build

      - name: Zip build folder
        run: |
          cd client
          zip -r build.zip build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: latest-build
          path: client/build.zip